-- Entertainment app schema. Run once in Supabase SQL Editor.
create table if not exists app_settings (id int primary key default 1, data jsonb not null default '{}'::jsonb);
create table if not exists activities (id bigint generated by default as identity primary key, day int, category text, name text, description text, "desc" text, location text, time text, capacity int default 0, entertainer text, image text, highlight boolean default false);
create table if not exists bookings (id bigint generated by default as identity primary key, activity_id bigint references activities(id) on delete cascade, room text, guest_name text, phone text, nationality text, adults int default 1, children int default 0, status text default 'booked', created_at timestamptz default now());
create table if not exists reviews (id bigint generated by default as identity primary key, activity_id bigint references activities(id) on delete cascade, room text, guest_name text, rating int check (rating between 1 and 5), comment text, created_at timestamptz default now());
create table if not exists app_users (id bigint generated by default as identity primary key, username text unique, password text, password_hash text, role text, display_name text, last_login timestamptz);
create table if not exists rooms (id bigint generated by default as identity primary key, room text, active boolean default true);
create table if not exists guest_accounts (id bigint generated by default as identity primary key, room text unique, name text, phone text, nationality text, arrival date, departure date, username text unique, password text, password_hash text, reset_required boolean default false);
create table if not exists tickets (id bigint generated by default as identity primary key, day int, name text, "desc" text, location text, time text, price text, capacity int default 0, image text);
create table if not exists ticket_orders (id bigint generated by default as identity primary key, ticket_id bigint references tickets(id) on delete cascade, room text, guest_name text, nationality text, qty int default 1, status text default 'reserved');
create table if not exists messages (id bigint generated by default as identity primary key, room text, sender text, sender_name text, text text, read_by_team boolean default false, read_by_guest boolean default false, created_at timestamptz default now());
create table if not exists requests (id bigint generated by default as identity primary key, room text, guest_name text, type text, detail text, date text, note text, status text default 'new', created_at timestamptz default now());
create table if not exists tasks (id bigint generated by default as identity primary key, title text, "desc" text, assigned_to text, due date, status text default 'open', created_at timestamptz default now());
create table if not exists announcements (id bigint generated by default as identity primary key, title text, body text, audience text default 'all', created_at timestamptz default now());
create table if not exists attendance (id bigint generated by default as identity primary key, booking_id bigint references bookings(id) on delete cascade, date date, present boolean default true);

create table if not exists audit_logs (id bigint generated by default as identity primary key, actor text, action text, entity text, entity_id text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists payroll_records (id bigint generated by default as identity primary key, user_id bigint references app_users(id) on delete set null, month text, salary numeric default 0, bonuses numeric default 0, deductions numeric default 0, overtime_hours numeric default 0, vacation_days numeric default 0, entrance_day date, dress_code text, status text default 'draft', created_at timestamptz default now());
create table if not exists locations (id bigint generated by default as identity primary key, name text, description text, photos jsonb default '[]'::jsonb, opening_hours text, directions text, lat numeric, lng numeric, active boolean default true);
create table if not exists files (id bigint generated by default as identity primary key, name text, type text, url text, folder text, created_at timestamptz default now());

-- Backfill columns for projects that already had older versions of these tables.
alter table app_users add column if not exists username text;
alter table app_users add column if not exists password text;
alter table app_users add column if not exists password_hash text;
alter table app_users add column if not exists role text;
alter table app_users add column if not exists display_name text;
alter table app_users add column if not exists last_login timestamptz;
alter table guest_accounts add column if not exists room text;
alter table guest_accounts add column if not exists name text;
alter table guest_accounts add column if not exists phone text;
alter table guest_accounts add column if not exists nationality text;
alter table guest_accounts add column if not exists arrival date;
alter table guest_accounts add column if not exists departure date;
alter table guest_accounts add column if not exists username text;
alter table guest_accounts add column if not exists password text;
alter table guest_accounts add column if not exists password_hash text;
alter table guest_accounts add column if not exists reset_required boolean default false;

-- Public API permissions for this single-file app.
-- Keep this project dedicated to the entertainment app because the publishable key is used in the browser.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;

-- Starter live data so the app is usable immediately after running this setup script.
insert into app_settings (id, data)
values (1, '{"name":"Entertainment","subtitle":"Animation Team","weatherLocation":"Hurghada, Egypt"}'::jsonb)
on conflict (id) do update set data = app_settings.data || excluded.data;

insert into app_users (username, password, role, display_name)
select 'manager', '1234', 'manager', 'Entertainment Manager'
where not exists (select 1 from app_users where username = 'manager');
insert into app_users (username, password, role, display_name)
select 'team', '1234', 'staff', 'Entertainer'
where not exists (select 1 from app_users where username = 'team');

insert into rooms (room, active)
select room, true from (values ('4215'), ('4308'), ('4510'), ('4102'), ('4103')) as v(room)
where not exists (select 1 from rooms r where r.room = v.room);

insert into guest_accounts (room, name, phone, nationality, arrival, departure, username, password)
select '4215', 'Familie Weber', '', 'German', current_date - 4, current_date + 3, 'room4215', '4215'
where not exists (select 1 from guest_accounts where room = '4215');

insert into activities (day, category, name, "desc", location, time, capacity, entertainer, image, highlight)
select * from (values
  (0, 'morning', 'Morning Yoga', 'Gentle stretching with sea view. All levels welcome.', 'Beach Deck', '09:00', 15, 'Team', 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=60', false),
  (0, 'morning', 'Aqua Gym', 'Wake up the body in the pool — music, energy and good vibes.', 'Main Pool', '10:00', 20, 'Team', 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&q=60', true),
  (0, 'kids', 'Kids Club', 'Games, crafts and mini disco for our little guests (4–12).', 'Kids Club', '10:30', 25, 'Kids Team', 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&q=60', false),
  (0, 'afternoon', 'Beach Volleyball', 'Friendly tournament on the beach court. Join a team!', 'Beach Court', '15:00', 16, 'Team', 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&q=60', false),
  (0, 'evening', 'Dance Show', 'An evening full of lights, music and surprises on the big stage.', 'Amphitheatre', '21:00', 150, 'Show Team', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=60', false),
  (2, 'theme', 'Foam Party', 'The legendary foam party at the main pool — don''t miss it!', 'Main Pool', '14:30', 80, 'All Team', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=60', true),
  (5, 'theme', 'Neon Party', 'Glow sticks, UV lights and the best beats of the week.', 'Amphitheatre', '21:30', 120, 'All Team', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=60', true)
) as v(day, category, name, "desc", location, time, capacity, entertainer, image, highlight)
where not exists (select 1 from activities a where a.name = v.name and a.day = v.day and a.time = v.time);

insert into tickets (day, name, "desc", location, time, price, capacity, image)
select * from (values
  (6, 'Tombola', 'Our big Sunday raffle with amazing prizes — every ticket can win!', 'Amphitheatre', '20:00', '5 €', 0, 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=60'),
  (2, 'Bingo Night', 'Classic bingo with the team, prizes and lots of laughs.', 'Pool Bar', '18:00', '3 €', 60, 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=60'),
  (4, 'Disco Night', 'Dance until late — DJ, lights and the best party of the week.', 'Disco', '22:30', '8 €', 0, 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=60')
) as v(day, name, "desc", location, time, price, capacity, image)
where not exists (select 1 from tickets t where t.name = v.name and t.day = v.day and t.time = v.time);

insert into announcements (title, body, audience)
select 'Foam Party today!', '14:30 at the Main Pool — bring your swimsuit and good mood!', 'all'
where not exists (select 1 from announcements where title = 'Foam Party today!');
