-- Entertainment app schema. Run once in Supabase SQL Editor.
-- Project: https://ogxkrmvhozgqhdleyllw.supabase.co
-- The app uses the publishable key configured in index.html and talks to these tables
-- through Supabase REST. Do not put the database password in any frontend file.

create table if not exists hotels (id text primary key, name text not null, logo text, created_at timestamptz default now());
create table if not exists app_settings (id int primary key default 1, hotel_id text default 'ogxkrmvhozgqhdleyllw', data jsonb not null default '{}'::jsonb);
create table if not exists activities (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', day int, category text, name text, description text, desc text, location text, time text, capacity int default 0, entertainer text, image text, highlight boolean default false);
create table if not exists bookings (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', activity_id bigint references activities(id) on delete cascade, room text, guest_name text, phone text, nationality text, adults int default 1, children int default 0, status text default 'booked', created_at timestamptz default now());
create table if not exists reviews (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', activity_id bigint references activities(id) on delete cascade, room text, guest_name text, rating int check (rating between 1 and 5), comment text, created_at timestamptz default now());
create table if not exists app_users (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', username text unique, password text, role text, display_name text);
create table if not exists rooms (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', room text, active boolean default true);
create table if not exists guest_accounts (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', room text unique, name text, phone text, nationality text, arrival date, departure date);
create table if not exists tickets (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', day int, name text, desc text, location text, time text, price text, capacity int default 0, image text);
create table if not exists ticket_orders (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', ticket_id bigint references tickets(id) on delete cascade, room text, guest_name text, nationality text, qty int default 1, status text default 'reserved');
create table if not exists messages (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', room text, sender text, sender_name text, text text, read_by_team boolean default false, read_by_guest boolean default false, created_at timestamptz default now());
create table if not exists requests (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', room text, guest_name text, type text, detail text, date text, note text, status text default 'new', created_at timestamptz default now());
create table if not exists tasks (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', title text, desc text, assigned_to text, due date, status text default 'open', created_at timestamptz default now());
create table if not exists announcements (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', title text, body text, audience text default 'all', created_at timestamptz default now());
create table if not exists attendance (id bigint generated by default as identity primary key, hotel_id text default 'ogxkrmvhozgqhdleyllw', booking_id bigint references bookings(id) on delete cascade, date date, present boolean default true);

-- Public app policies for the publishable key. The app has its own simple role/room login.
alter table hotels enable row level security;
alter table app_settings enable row level security;
alter table activities enable row level security;
alter table bookings enable row level security;
alter table reviews enable row level security;
alter table app_users enable row level security;
alter table rooms enable row level security;
alter table guest_accounts enable row level security;
alter table tickets enable row level security;
alter table ticket_orders enable row level security;
alter table messages enable row level security;
alter table requests enable row level security;
alter table tasks enable row level security;
alter table announcements enable row level security;
alter table attendance enable row level security;

do $$
declare t text;
begin
  foreach t in array array['hotels','app_settings','activities','bookings','reviews','app_users','rooms','guest_accounts','tickets','ticket_orders','messages','requests','tasks','announcements','attendance'] loop
    execute format('drop policy if exists entertainment_public_all on %I', t);
    execute format('create policy entertainment_public_all on %I for all using (true) with check (true)', t);
  end loop;
end $$;

insert into hotels (id, name) values ('ogxkrmvhozgqhdleyllw', 'Entertainment') on conflict (id) do nothing;
insert into app_settings (id, hotel_id, data) values (1, 'ogxkrmvhozgqhdleyllw', '{"name":"Entertainment","subtitle":"Animation Team","hotelId":"ogxkrmvhozgqhdleyllw"}'::jsonb) on conflict (id) do nothing;
insert into app_users (username, password, role, display_name) values
  ('manager', '1234', 'manager', 'Entertainment Manager'),
  ('team', '1234', 'staff', 'Entertainer')
on conflict (username) do nothing;
insert into rooms (room, active) values ('4215', true), ('4308', true), ('4510', true), ('4102', true), ('4103', true) on conflict do nothing;

insert into activities (day, category, name, desc, location, time, capacity, entertainer, image, highlight)
select * from (values
  (0,'morning','Aqua Gym','Wake up the body in the pool — music, energy and good vibes.','Main Pool','10:00',20,'Team','https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=60',true),
  (0,'kids','Kids Club','Games, crafts and mini disco for our little guests (4–12).','Kids Club','10:30',25,'Kids Team','https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&q=60',false),
  (0,'evening','Dance Show','An evening full of lights, music and surprises on the big stage.','Amphitheatre','21:00',150,'Show Team','https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=60',false),
  (2,'theme','Foam Party','The legendary foam party at the main pool — don''t miss it!','Main Pool','14:30',80,'All Team','https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=60',true),
  (5,'theme','Neon Party','Glow sticks, UV lights and the best beats of the week.','Amphitheatre','21:30',120,'All Team','https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=60',true)
) as v(day, category, name, desc, location, time, capacity, entertainer, image, highlight)
where not exists (select 1 from activities where name = v.name and day = v.day and time = v.time);

insert into tickets (day, name, desc, location, time, price, capacity, image)
select * from (values
  (6,'Tombola','Our big Sunday raffle with amazing prizes — every ticket can win!','Amphitheatre','20:00','5 €',0,'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=60'),
  (2,'Bingo Night','Classic bingo with the team, prizes and lots of laughs.','Pool Bar','18:00','3 €',60,'https://images.unsplash.com/photo-1642056446459-59a5e696d97c?w=800&q=60')
) as v(day, name, desc, location, time, price, capacity, image)
where not exists (select 1 from tickets where name = v.name and day = v.day and time = v.time);
