-- Entertainment app schema. Run once in Supabase SQL Editor.
create table if not exists hotels (
  id text primary key,
  name text not null,
  logo text,
  created_at timestamptz default now()
);

create table if not exists app_settings (
  id int primary key default 1,
  hotel_id text default 'demo-hotel',
  data jsonb not null default '{}'::jsonb
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  day int,
  category text,
  name text,
  description text,
  "desc" text,
  location text,
  time text,
  capacity int default 0,
  entertainer text,
  image text,
  highlight boolean default false
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  activity_id bigint references activities(id) on delete cascade,
  room text,
  guest_name text,
  phone text,
  nationality text,
  adults int default 1,
  children int default 0,
  status text default 'booked',
  created_at timestamptz default now()
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  activity_id bigint references activities(id) on delete cascade,
  room text,
  guest_name text,
  rating int check (rating between 1 and 5),
  comment text,
  created_at timestamptz default now()
);

create table if not exists app_users (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  username text unique,
  password text,
  role text,
  display_name text
);

create table if not exists rooms (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  room text,
  active boolean default true
);

create table if not exists guest_accounts (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  room text unique,
  name text,
  phone text,
  nationality text,
  arrival date,
  departure date
);

create table if not exists tickets (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  day int,
  name text,
  "desc" text,
  location text,
  time text,
  price text,
  capacity int default 0,
  image text
);

create table if not exists ticket_orders (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  ticket_id bigint references tickets(id) on delete cascade,
  room text,
  guest_name text,
  nationality text,
  qty int default 1,
  status text default 'reserved'
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  room text,
  sender text,
  sender_name text,
  text text,
  read_by_team boolean default false,
  read_by_guest boolean default false,
  created_at timestamptz default now()
);

create table if not exists requests (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  room text,
  guest_name text,
  type text,
  detail text,
  date text,
  note text,
  status text default 'new',
  created_at timestamptz default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  title text,
  "desc" text,
  assigned_to text,
  due date,
  status text default 'open',
  created_at timestamptz default now()
);

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  title text,
  body text,
  audience text default 'all',
  created_at timestamptz default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  hotel_id text default 'demo-hotel',
  booking_id bigint references bookings(id) on delete cascade,
  date date,
  present boolean default true
);
